#!/bin/sh
#
# bspwmrc

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
monitors

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config border_width 2
bspc config window_gap 16
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

source ~/.config/bar/config
bspc config focused_border_color "$color7"
bspc config normal_border_color "$color0"
bspc config active_border_color "$color8"
bspc config presel_feedback_color "$color15"

pgrep -x bar > /dev/null || status-bar &
