unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"
set -as terminal-overrides ",xterm-ghostty:Tc"

set -g set-titles on
set -g base-index 1
set -g renumber-windows on
set -g mouse on

set -g status-style bg=default
set -g status-style fg=default

# set -g status-bg default
# set -g status-fg default
# set -g status-fg colour137
# set -g status-left ''
# set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
# set -g status-right-length 50
# set -g status-left-length 20
# setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
# setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

bind r source-file "~/.config/tmux/tmux.conf"
bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind -n M-q kill-pane
bind -n M-r command-prompt "rename-window -- '%%'"
bind -n M-1 if-shell "tmux select-window -t :1" "" "new-window -t :1"
bind -n M-2 if-shell "tmux select-window -t :2" "" "new-window -t :2"
bind -n M-3 if-shell "tmux select-window -t :3" "" "new-window -t :3"
bind -n M-4 if-shell "tmux select-window -t :4" "" "new-window -t :4"
bind -n M-5 if-shell "tmux select-window -t :5" "" "new-window -t :5"
bind -n M-6 if-shell "tmux select-window -t :6" "" "new-window -t :6"
bind -n M-7 if-shell "tmux select-window -t :7" "" "new-window -t :7"
bind -n M-8 if-shell "tmux select-window -t :8" "" "new-window -t :8"
bind -n M-9 if-shell "tmux select-window -t :9" "" "new-window -t :9"
bind -n M-0 if-shell "tmux select-window -t :10" "" "new-window -t :10"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'
