#!/bin/sh
#
# xinitrc

xset r rate 200 50
#xset m 1/1 0
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape
xrdb ~/.config/xres/xresources

sxhkd &
unclutter &
picom -b
setroot --restore

exec bspwm
